app/users/forms.py
#
# users/forms.py - form definitions for user management related functions
#
from flask import current_app
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, SelectField, HiddenField, ValidationError
from wtforms_sqlalchemy.fields import QuerySelectField
from wtforms.validators import DataRequired, Email, EqualTo, Length, Optional, Regexp
from app.models import User, UserRole  # Import the UserRole enum

# Custom Validator Function
def validate_password_length(form, field):
    min_length = current_app.config['MIN_PASSWORD_LENGTH']
    if len(field.data) < min_length:
        raise ValidationError(f'Password must be at least {min_length} characters long.')

def validate_current_password(self, field):
    if not current_user.check_password(field.data):
        raise ValidationError('Incorrect current password.')

def role_query():
    return UserRole.querys

def coerce_user_role(name):
    print(name)
    for role in UserRole:
        print(">>", role.name)
        if role.name == name:
            return role
    raise ValueError("Invalid UserRole")

class UserForm(FlaskForm):
    id = HiddenField('User ID')
    username = StringField('Username', validators=[DataRequired(), Length(min=3, max=20)])

    given_name = StringField('Given Name', validators=[DataRequired(), Length(min=1, max=64)])
    surname = StringField('Surname', validators=[DataRequired(), Length(min=1, max=64)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    phone = StringField('Phone', validators=[DataRequired(), Length(min=1, max=20), Regexp('^[0-9\-\+]+$', message="Phone number must contain only numbers and -/+ characters")])

    role = SelectField('Role', coerce=str, choices=[(role, role.value) for role in UserRole], validators=[DataRequired()])
    

# adds the specific functionality for adding new users
class AddUserForm(UserForm):
    password = PasswordField('Password', validators=[
        DataRequired(),
        validate_password_length  # Custom validator for minimum length
    ])
    password2 = PasswordField('Confirm Password', validators=[
        DataRequired(),
        EqualTo('password', message='Passwords must match.')
    ])


# adds the specific functionality for editing user accounts
class EditUserForm(UserForm):
    new_password = PasswordField('New Password', validators=[Optional(), validate_password_length])
    new_password2 = PasswordField('Confirm New Password', validators=[Optional(), EqualTo('new_password', message='Passwords must match')])

    def validate_new_password(form, field):
        if field.data and not form.new_password2.data:
            raise ValidationError("Please confirm the new password.")
                

# functionality for changing user's password
class ChangePasswordForm(FlaskForm):
    old_password = PasswordField('Current Password', validators=[
        DataRequired(),
        validate_current_password])
    new_password = PasswordField('New Password', validators=[
        DataRequired(),
        validate_password_length  # Custom validator for minimum length
    ])
    new_password2 = PasswordField('Confirm New Password', validators=[
        DataRequired(),
        EqualTo('new_password', message='Passwords must match.')
    ])
    submit = SubmitField('Change Password')

app/users/__init__.py
from flask import Blueprint

bp_users = Blueprint('users', __name__, url_prefix='/users')

from app.users import routes

app/users/routes.py
from flask import render_template, redirect, url_for, flash, request, current_app
from flask_login import login_required, current_user
from flask_paginate import Pagination, get_page_parameter
from werkzeug.security import check_password_hash
from . import bp_users
from .forms import AddUserForm, ChangePasswordForm, EditUserForm, UserForm
from sqlalchemy.exc import SQLAlchemyError
from app.models import User, UserRole
from app.decorators import role_required
from app import db

# User related forms are:
# view users, add user, edit user - access for ADMIN role only
# change password - access to all authenticated users (can change only own password)

@bp_users.route('/view')
@role_required(UserRole.ADMIN)
def view_users():
    items_per_page = current_app.config['ITEMS_PER_PAGE']
    page = request.args.get('page', 1, type=int)
    users = User.query.paginate(page=page, per_page=items_per_page, error_out=False)
    return render_template('users/view_users.html', users=users.items, pagination=users)


# Add User Route
@bp_users.route('/add', methods=['GET', 'POST'])
@role_required(UserRole.ADMIN)
def add_user():
    form = AddUserForm()
    if form.validate_on_submit():
        try:
            new_user = User(
                username=form.username.data,
                email=form.email.data,
                role=form.role.data,
                given_name=form.given_name.data,
                surname=form.surname.data,
                phone=form.phone.data
            )
            new_user.set_password(form.password.data)  # Set the password
            db.session.add(new_user)
            db.session.commit()
            return redirect(url_for('users.view_users'))
            
            # return render_template('users/add_user.html', form=form, user_added=True, submit_button_text="Add")

        except SQLAlchemyError as e:
            print(e)
            db.session.rollback()  # Rollback the session
        finally:
            # Close the session if you are done with it, especially if it's not scoped to the request
            db.session.close()

    else:
        for fieldName, errorMessages in form.errors.items():
            for err in errorMessages:
                print(f"Error in {fieldName}: {err}")

    return render_template('users/add_user.html', form=form, action="Add", submit_button_text="Add")



# Edit User Route
@bp_users.route('/edit/<int:user_id>', methods=['GET', 'POST'])
@role_required(UserRole.ADMIN)
def edit_user(user_id):
    user = User.query.get_or_404(user_id)
    print("Username and role before rendering the form:", user.username, user.role.name)
    # user_role = user.role.name if user.role else None
    form = EditUserForm(obj=user)

    if form.validate_on_submit():
        user.username = form.username.data
        user.given_name = form.given_name.data
        user.surname = form.surname.data
        user.email = form.email.data
        user.phone = form.phone.data
        # user.role = form.role
        user.role = form.role.data
        print(user.role)
        if form.new_password.data:
            user.set_password(form.new_password.data)
        print(user)
        db.session.commit()

        return redirect(url_for('users.view_users'))
    print('invalid form')
    return render_template('users/edit_user.html', form=form, action="Edit", submit_button_text="Ok", user_id=user_id)

# Delete user route
@bp_users.route('/delete/<int:user_id>', methods=['GET', 'POST'])
@role_required(UserRole.ADMIN)
def delete_user(user_id):
    print("deleting user", user_id)
    user = User.query.get_or_404(user_id)

    if current_user.id == user_id:
        form = EditUserForm(obj=user)
        delete_self_error_message = "You cannot delete your own account."
        return render_template('users/edit_user.html', 
                               form=form, 
                               user_id=user_id, 
                               delete_self_error_message=delete_self_error_message,
                               submit_button_text="Ok")

    try:
        db.session.delete(user)
        db.session.commit()
        # Redirect to view_users with a flag to trigger the JavaScript success popup
        return redirect(url_for('users.view_users', user_deleted=True))
    except Exception as e:
        print(f"Error deleting user: {e}")  # Use logging in production
        form = EditUserForm(obj=user)
        # Return to the edit_user page with a Bootstrap alert for error
        return render_template('users/edit_user.html', form=form, user_id=user_id, delete_error=True)


# Change Password route
@bp_users.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        
        if not current_user.check_password(form.old_password.data):
            flash('Incorrect current password.')
            return render_template('users/change_password.html', form=form)
        
        current_user.set_password(form.new_password.data)  # Set the new password
        db.session.commit()  # Commit the changes to the database
        # flash('Password changed successfully.')
        return render_template('users/change_password.html', form=form, password_changed=True)
        # return redirect(url_for('main.dashboard'))
    return render_template('users/change_password.html', form=form, action="Change Password")

app/templates/users/add_user.html
{% extends "users/user_form.html" %}


{% block priority_fields %}
<div class="form-group row mb-3">
    {{ form.username.label(class="col-sm-6 col-form-label fs-14") }}
    <div class="col-sm-6">
        {{ form.username(class="form-control fs-12") }}
    </div>
</div>

{% endblock %}

{% block additional_fields %}
<div class="form-group row mb-3">
    {{ form.password.label(class="col-sm-6 col-form-label fs-14") }}
    <div class="col-sm-6">
        {{ form.password(class="form-control fs-12") }}
    </div>
</div>
{% if form.password.errors %}
<div class="alert alert-danger col-sm-4 fs-12 mt-2">
    {% for error in form.password.errors %}
        <span>{{ error }}</span>
    {% endfor %}
</div>
{% endif %}
<div class="form-group row mb-3">
    {{ form.password2.label(class="col-sm-6 col-form-label fs-14") }}
    <div class="col-sm-6">
        {{ form.password2(class="form-control fs-12") }}
    </div>
</div>
{% if form.password2.errors %}
<div class="alert alert-danger col-sm-4 fs-12 mt-2">
    {% for error in form.password2.errors %}
        <span>{{ error }}</span>
    {% endfor %}
</div>
{% endif %}

<script>
    {% if user_added %}
        alert('User added successfully.');
        window.location.href = "{{ url_for('users.view_users') }}";
    {% endif %}
</script>


{% endblock %}

{% block additional_buttons %}
<!--     <button type="submit" class="btn btn-ok mt-3" name="submit_add_next" value="add_next">Save & Add Next</button> -->
{% endblock %}

app/templates/users/change_password.html
{% extends "base.html" %}

{% block content %}
  
<div class="container">
    <div class="card card-width-changepass mb-4">
        <div class="card-header">
            <h6>{{ action }}</h6>
        </div>
        <div class="card-body">
            <form method="post" class="form-horizontal">
                
                {{ form.hidden_tag() }}

                <div class="form-group row mb-3">
                    {{ form.old_password.label(class="col-sm-6 col-form-label fs-14") }}
                    <div class="col-sm-6">
                        {{ form.old_password(class="form-control fs-12") }}
                        {% if form.old_password.errors %}
                        <div class="alert alert-danger fs-12 mt-2">
                            {% for error in form.old_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                </div>

                <div class="form-group row mb-3">
                    {{ form.new_password.label(class="col-sm-6 col-form-label fs-14") }}
                    <div class="col-sm-6">
                        {{ form.new_password(class="form-control fs-12") }}
                        {% if form.new_password.errors %}
                        <div class="alert alert-danger fs-12 mt-2">
                            {% for error in form.new_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                </div>

                <div class="form-group row mb-3">
                    {{ form.new_password2.label(class="col-sm-6 col-form-label fs-14") }}
                    <div class="col-sm-6">
                        {{ form.new_password2(class="form-control fs-12") }}
                        {% if form.new_password2.errors %}
                        <div class="alert alert-danger fs-12 mt-2">
                            {% for error in form.new_password2.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-12">
                        <div class="d-flex justify-content-start">
                            <button type="button" class="btn btn-sm btn-light mt-2" onclick="confirmCancel('{{ url_for('main.dashboard') }}')">Cancel</button>
                            <button type="submit" class="btn btn-sm btn-primary mt-2 ms-2" onclick="return confirmSubmitUserData()" name="submit" value="save">{{ action }}</button>
                        </div>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>

<script>
    {% if password_changed %}
        alert('Your password has been changed successfully.');
        window.location.href = "{{ url_for('main.dashboard') }}";
    {% endif %}
</script>

<script src="{{ url_for('static', filename='form_utils.js') }}"></script>

<!-- scripts to confirm or to cancel password change. -->    

{% endblock %}

app/templates/users/edit_user.html
{% extends "users/user_form.html" %}

{% block priority_fields %}
    <div class="form-group row mb-3">
        {{ form.username.label(class="col-sm-6 col-form-label fs-14") }}
        <div class="col-sm-6">
            {{ form.username(class="form-control fs-12", disabled=true) }}

        </div>
    </div>

    {% if delete_self_error_message %}
    <div class="alert alert-danger" role="alert">
        {{ delete_self_error_message }}
    </div>
    {% endif %}

    {% if delete_error %}
        <div class="alert alert-danger" role="alert">
            An error occurred during the deletion process.
        </div>
    {% endif %}

{% endblock %}


{% block additional_fields %}

    <div id="passwordChangeSection" style="display: none;">
        <div class="form-group row mb-3">
            {{ form.new_password.label(class="col-sm-6 col-form-label fs-14") }}
            <div class="col-sm-6">
                {{ form.new_password(class="form-control fs-12", disabled=true, id="newPassword") }}
            </div>
        </div>
        {% if form.new_password.errors %}
        <div class="alert alert-danger col-sm-4 fs-12 mt-2">
            {% for error in form.new_password.errors %}
                <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% endif %}
        <div class="form-group row mb-3">
            {{ form.new_password2.label(class="col-sm-6 col-form-label fs-14") }}
            <div class="col-sm-6">
                {{ form.new_password2(class="form-control fs-12", disabled=true, id="newPassword2") }}
            </div>
        </div>
        {% if form.new_password2.errors %}
        <div class="alert alert-danger col-sm-4 fs-12 mt-2">
            {% for error in form.new_password2.errors %}
                <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% endif %}
    </div>

{% endblock %}

{% block additional_buttons %}
    <button type="button" id="togglePasswordChangeButton" class="btn btn-sm btn-light ms-2 mt-2" onclick="togglePasswordChange()">Enable Password Change</button>
    {% if current_user.id != user_id %}
        <button type="button" class="btn btn-sm btn-danger ms-2 mt-2" onclick="confirmDeleteUser({{ user_id }})">Delete</button>
    {% endif %}

{% endblock %}

{% block additional_scripts %}

<script>
    function togglePasswordChange() {
        var passwordChangeSection = document.getElementById('passwordChangeSection');
        var newPasswordField = document.getElementById('newPassword');
        var confirmNewPasswordField = document.getElementById('newPassword2');
        var toggleButton = document.getElementById('togglePasswordChangeButton');

        if (newPasswordField.disabled) {
            // Enable password change
            if (confirm('Are you sure you want to enable password change?')) {
                passwordChangeSection.style.display = 'block';
                newPasswordField.disabled = false;
                confirmNewPasswordField.disabled = false;
                toggleButton.textContent = 'Disable Password Change';
            }
        } else {
            // Disable password change
            passwordChangeSection.style.display = 'none';
            newPasswordField.disabled = true;
            confirmNewPasswordField.disabled = true;
            newPasswordField.value = '';
            confirmNewPasswordField.value = '';
            toggleButton.textContent = 'Enable Password Change';
        }
    }
</script>

<script>
    function confirmDeleteUser(userId) {
        if(confirm('Are you sure you want to delete this user?')) {
            var deleteUrl = "{{ url_for('users.delete_user', user_id=0) }}".replace('0', userId);
            window.location.href = deleteUrl;
        }
    }
</script>


{% endblock %}

app/templates/users/user_form.html
<!-- user_form.html -->
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="card card-width-userform mb-4">
        <div class="card-header">
            <h6>{{ action }}</h6>
        </div>
        <div class="card-body">
            <form method="post" class="form-horizontal">
                {{ form.hidden_tag() }}
                {% block priority_fields %}
                {% endblock %}

                <!-- Each form group is a row, with labels and inputs as columns -->
                
                <div class="form-group row mb-3">
                    {{ form.given_name.label(class="col-sm-6 col-form-label fs-14") }}
                    <div class="col-sm-6">
                        {{ form.given_name(class="form-control fs-12") }}
                    </div>
                </div>
                
                <div class="form-group row mb-3">
                    {{ form.surname.label(class="col-sm-6 col-form-label fs-14") }}
                    <div class="col-sm-6">
                        {{ form.surname(class="form-control fs-12") }}
                    </div>
                </div>

                <div class="form-group row mb-4">
                    {{ form.email.label(class="col-sm-6 col-form-label fs-14") }}
                    <div class="col-sm-6">
                        {{ form.email(class="form-control fs-12") }}
                    </div>
                </div>

                <div class="form-group row mb-4">
                    {{ form.phone.label(class="col-sm-6 col-form-label fs-14") }}
                    <div class="col-sm-6">
                        {{ form.phone(class="form-control fs-12") }}
                    </div>
                </div>

                <div class="form-group row mb-4">
                    {{ form.role.label(class="col-sm-6 col-form-label fs-14") }}
                    <div class="col-sm-6">
                        {{ form.role(class="form-control fs-12") }}
                    </div>
                </div>

                {% block additional_fields %}
                    <!-- Additional fields will be defined in child templates -->
                {% endblock %}


                <div class="form-group row">
                    <div class="col-sm-12">
                        <div class="d-flex justify-content-start">
                            <button type="button" class="btn btn-sm btn-light mt-2" onclick="confirmCancel('{{ url_for('users.view_users') }}')">Cancel</button>

                            {% block additional_buttons %}
                                <!-- Additional buttons will be defined in child templates -->
                            {% endblock %}
<!--                             <button type="submit" class="btn btn-sm btn-primary mt-2 ms-2" name="submit" value="save">{{ action }}</button> -->
                            <button type="submit" class="btn btn-sm btn-primary mt-2 ms-2" name="submit" value="save" onclick="return confirmSubmitChanges()">{{ submit_button_text }}</button>

                        </div>
                    </div>
                </div>
                
                {% block userform_scripts %}

                <script src="{{ url_for('static', filename='form_utils.js') }}"></script>


                {% endblock %}        
        

                {% block additional_scripts %}
                {% endblock %}
                
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/users/view_users.html
{% extends "base.html" %}

{% block content %}

<div class="card">
    <div class="card-header">
        <h6>View/Edit Users</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-light table-sm table-hover table-striped">
                <thead class="custom-table-header">
                    <tr>
                        <th>Username</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th>Last login</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    <tr class="custom-table-row" ondblclick="window.location='{{ url_for('users.edit_user', user_id=user.id) }}'">
                        <td>{{ user.username }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.role.value }}</td>
                        <td>{{ user.last_logon_as_str() }}</td>
                        <td>
                            <a href="{{ url_for('users.edit_user', user_id=user.id) }}" class="btn btn-sm btn-link">Edit</a>
                            <!-- Delete button can be added here if needed -->
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <!-- Pagination controls -->
        {% if pagination %}
        <nav>
            <ul class="pagination custom-pagination pagination-sm">
                {% for page in pagination.iter_pages() %}
                    {% if page %}
                        <li class="page-item{% if page == pagination.page %} active{% endif %}">
                            <a class="page-link" href="{{ url_for('users.view_users', page=page) }}">{{ page }}</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled"><span class="page-link">…</span></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </nav>
        {% endif %}
    </div>
</div>

{% endblock %}

{% block additional_scripts %}
{% if user_deleted %}
<script>
    alert("User deleted successfully.");
</script>
{% endif %}
{% endblock %}